apiVersion: v1
kind: Service
metadata:
  labels:
    run: red
  name: red-svc-ci
  namespace: colour
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: red

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: green
  name: green-svc-ci
  namespace: colour
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: green